db:
  used: "postgre"
  postgre:
    host: "127.0.0.1"
    port: 5432
    db_name: "aimlink"
    usr: "postgres"
    passwd: "postgres"
    max_idle_conns: 5
    max_open_conns: 10 
transport:
  mqtt:
    bind: "false"
    broker: 
    clientid: ""
    encrypt: ""
    passwd: 
    qos: 0
    usr: 
webserver:
  bind_address: ":8082"
  ssl: false
  ssl_cert_file: ""
  ssl_key_file: "" 
